name: Production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages & build prod ng app
        run: |
          npm install
          npm run build:prod
          ls
      - name: Archive production artifacts
        uses: actions/upload-pages-artifact@v0
        with:
          name: dist-folder
          path: |
            ./docs/_site
          retention-days: 1
